#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null
cd "$SCRIPTPATH/.."

docker run --rm -it -u `id -u` -v $PWD/:/app caseyamcl/phar-builder package -n --output-dir=/app/dist \
    --entry-point=/app/index.php --name=iggy.phar -f --include=src --skip-shebang=0 $@ composer.json

chmod +x "$SCRIPTPATH/../dist/iggy.phar"